### PR TITLE
fix unicode strings in symbol_previous and symbol_next

### PR DESCRIPTION
**Pull request by dcere**
If a unicode string is used to represent the previous and next symbols, it will be translated to an html-escaped string with ascii encoding. This way, the user is not restricted to use html-escaped ascii strings in their previous and next symbols.

### CODE REVIEW

**Comment by ergo** [comment]
Hello @dcere,

I looked at your patch (thank you for your PR), and while it looks OK to me I have another idea.
Since the world moves toward Python 3, maybe it would be better if I replace all str() calls , into unicode instead?
str() was what the library was doing before I inherited the codebase, so I followed the convention but I think that gettring rid of this behavior would be a better solution long term.

**Comment by ergo** [comment]
@dcere 

I've fixed this in https://github.com/Pylons/paginate/commit/3ebd14314c6e877f4ec1908ebe81901f110486fe.

I've changed the default behavior and tested under python 2.7 and 3.5 - using jinja2 renderer for the paginator in my templates.
Can you try pulling the trunk version and see if everything is working for you?
If everything is in order I can make a release tommorow.

**Comment by dcere** [comment]
Yes, it is working for me too. Thank you!

I consider this as solved, so you can close it when you think it is best.

**Comment by ergo** [comment]
I've made a new release.
So closing

**Pull request closed without merging**
